# Exercício

In [49]:
# Importando a biblioteca numpy
import numpy as np

In [2]:
#1. Crie um array NumPy unidimensional com os números de 1 a 10.
array = np.arange(1,11)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
#2. Crie um array NumPy bidimensional 3x3 preenchido com zeros.
array = np.random.random((3,3))*0

array2 = np.zeros((3,3))
x = np.full((3,3),0)
print(array2)
print(array)
print(x)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [26]:
#3. Crie um array NumPy bidimensional 4x4 preenchido com uns.
array2 = np.zeros((4,4))+1

x = np.array([1,1,1,1])
x = np.tile(x,(4,1))
y = np.full((4,4),1)
print(array2)
print(x)
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [72]:
# Crie um array NumPy com 20 valores aleatórios entre 0 e 100.
array = np.random.random((20))*100
array2 = np.random.randint(0,100,20)
print(array)
print(array2)

[53.87664821 37.19402783 40.09784843 41.1686449  50.82176728 84.53648923
 10.08113817 53.26377964  6.22958189 72.95137581 79.79601665 82.80594653
 59.98340052 49.678838   50.17075733 99.37274371 45.78382074 84.44726426
 63.31063793 62.99361533]
[ 8  5 94 31 95 50 72 79  7 87 57 43 37 93 72 85 13 46  1 29]


In [29]:
# Crie um array NumPy unidimensional com espaçamento de 0.5 entre 0 e 10
array = np.arange(0,10,0.5)
array

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [76]:
# Crie um array NumPy bidimensional 5x5 com valores aleatórios inteiros entre 1 e 100.
array = np.random.randint(1,101,(5,5))


print(array)


[[57 91 66 89 51]
 [85 12 53 71 15]
 [90  9 27 61 23]
 [52 30 52  1  7]
 [ 7  1 56 59 60]]


In [52]:
#7. Dada a matriz A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]], crie um array NumPy contendo apenas a segunda coluna da matriz A.
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = A[:,1]
B

array([2, 5, 8])

In [64]:
#8. Dado o array NumPy x = [1, 2, 3, 4, 5], crie um novo array onde todos os valores pares sejam substituídos por -1.
x = np.array([1, 2, 3, 4, 5])
x[x%2] = -1
x
y= np.array([1, 2, 3, 4, 5])
b = np.where(y%2,-1,y)
print(x)
print(b)

[-1 -1  3  4  5]
[-1  2 -1  4 -1]


In [65]:
#9.  Dado o array NumPy x = [1, 2, 3, 4, 5], crie um novo array onde todos os valores maiores que 2 sejam substituídos por 0.
x = np.array([1, 2, 3, 4, 5])
x[x>2] = 0
x

array([1, 2, 0, 0, 0])

In [ ]:
#10. Dado o array NumPy x = [1, 2, 3, 4, 5], normalize os valores do array de forma que a soma seja igual a 1.
x = np.array([1, 2, 3, 4, 5])

In [66]:
#11. Dada a matriz A = [[1, 2], [3, 4]] e a matriz B = [[5, 6], [7, 8]], calcule a multiplicação matricial entre A e B.
A = np.array([[1, 2], [3, 4]] )
B = np.array([[5, 6], [7, 8]])
print(A*B)
print(np.multiply(A,B))
print(np.dot(A,B))


[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [69]:
#12. Dado o array NumPy x = [1, 2, 3], crie um novo array com os valores de x repetidos três vezes.
x = np.array([1, 2, 3])
print(np.repeat(x,3))


[1 1 1 2 2 2 3 3 3]


In [68]:
#13. Dado o array NumPy x = [1, 2, 3], crie um novo array com os valores de x repetidos lado a lado três vezes.


x = np.array([1, 2, 3])
print(np.repeat(x,3))

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
#14. Dado o array NumPy x = [1, 2, 3], crie um novo array com os valores de x repetidos verticalmente três vezes.
x = np.array([1, 2, 3])
print(np.tile(x,(3,1)))

In [70]:
#15. Dado o array NumPy x = [1, 2, 3], inverta a ordem dos elementos do array.
x = np.array([1, 2, 3])
print(np.flip(x))

[3 2 1]


1. Crie um array NumPy unidimensional com os números de 1 a 10.
   
2. Crie um array NumPy bidimensional 3x3 preenchido com zeros.
   
3. Crie um array NumPy bidimensional 4x4 preenchido com uns.
   
4. Crie um array NumPy com 20 valores aleatórios entre 0 e 100.
5. Crie um array NumPy unidimensional com espaçamento de 0.5 entre 0 e 10.
6. Crie um array NumPy bidimensional 5x5 com valores aleatórios inteiros entre 1 e 100.
7. Dada a matriz A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]], crie um array NumPy contendo apenas a segunda coluna da matriz A.
8. Dado o array NumPy x = [1, 2, 3, 4, 5], crie um novo array onde todos os valores pares sejam substituídos por -1.
9.  Dado o array NumPy x = [1, 2, 3, 4, 5], crie um novo array onde todos os valores maiores que 2 sejam substituídos por 0.
10. Dado o array NumPy x = [1, 2, 3, 4, 5], normalize os valores do array de forma que a soma seja igual a 1.
11. Dada a matriz A = [[1, 2], [3, 4]] e a matriz B = [[5, 6], [7, 8]], calcule a multiplicação matricial entre A e B.
12. Dado o array NumPy x = [1, 2, 3], crie um novo array com os valores de x repetidos três vezes.
13. Dado o array NumPy x = [1, 2, 3], crie um novo array com os valores de x repetidos lado a lado três vezes.
14. Dado o array NumPy x = [1, 2, 3], crie um novo array com os valores de x repetidos verticalmente três vezes.
15. Dado o array NumPy x = [1, 2, 3], inverta a ordem dos elementos do array.